### ISSUE TITLE
Panning in output

### ISSUE THREAD

**Issue by s-kumar16** [andrmor/ANTS2#73]
In output(results), panning is not possible for PM signals viz.

![Capturar](https://user-images.githubusercontent.com/48560184/54367126-c5780b80-4669-11e9-8b89-889eb6d2fad2.PNG)

**Comment by andrmor** [comment]
Please check my fix at the Dev branch.
Panning should work now. I have also changed the default behavior: the panning/zoom settings will be remembered until a new detector is loaded.
